### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by astaykov** [thinktecture/Thinktecture.IdentityServer.v3.Admin#1]
Is there already something decided for the admin? Or is it just on the roadmap?
Do you plan to develop it as a plugin?
I was thinking on Admin UI, so I will be happy to contribute.

**Comment by brockallen** [comment]
Yes, this repo models the admin functionality. It will involve a core, a UI, and a persistence layer.

**Comment by IWriteApps** [comment]
Is this intended to replace IdentityManager?

**Comment by brockallen** [comment]
No. IdentityManager manages users. This repo manages the config for IdentityServer (clients, scopes, etc).

**Comment by 2masbaali** [comment]
When I Run Admin code I see "HTTP Error 500.0 - Internal Server Error". how can I solve it?
